sudo: required
services:
    - docker

before_install:
    - docker build -t jacksinn/dk -f Dockerfile.dev .

script:
    - docker run -e CI=true jacksinn/dk npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-976520447513"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
